import type { Level } from '../src/types/level';
import type { TopicId } from '../src/types/topic';

export const levelsByTopic: Record<TopicId, Level[]> = {
  fundamentals: [
    {
      id: 'fundamentals_1',
      topicId: 'fundamentals',
      number: 1,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 5, y: 80 },
      connections: ['fundamentals_2'],
    },
    {
      id: 'fundamentals_2',
      topicId: 'fundamentals',
      number: 2,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 13, y: 60 },
      connections: ['fundamentals_3'],
    },
    {
      id: 'fundamentals_3',
      topicId: 'fundamentals',
      number: 3,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 20, y: 75 },
      connections: ['fundamentals_4'],
    },
    {
      id: 'fundamentals_4',
      topicId: 'fundamentals',
      number: 4,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 25, y: 60 },
      connections: ['fundamentals_5'],
    },
    {
      id: 'fundamentals_5',
      topicId: 'fundamentals',
      number: 5,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 30, y: 45 },
      connections: ['fundamentals_6'],
    },
    {
      id: 'fundamentals_6',
      topicId: 'fundamentals',
      number: 6,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 40, y: 30 },
      connections: ['fundamentals_7'],
    },
    {
      id: 'fundamentals_7',
      topicId: 'fundamentals',
      number: 7,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 45, y: 45 },
      connections: ['fundamentals_8'],
    },
    {
      id: 'fundamentals_8',
      topicId: 'fundamentals',
      number: 8,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 52, y: 38 },
      connections: ['fundamentals_9'],
    },
    {
      id: 'fundamentals_9',
      topicId: 'fundamentals',
      number: 9,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 58, y: 50 },
      connections: ['fundamentals_10'],
    },
    {
      id: 'fundamentals_10',
      topicId: 'fundamentals',
      number: 10,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 68, y: 55 },
      connections: ['fundamentals_11'],
    },
    {
      id: 'fundamentals_11',
      topicId: 'fundamentals',
      number: 11,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 73, y: 45 },
      connections: ['fundamentals_12'],
    },
    {
      id: 'fundamentals_12',
      topicId: 'fundamentals',
      number: 12,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 75, y: 30 },
      connections: ['fundamentals_13'],
    },
    {
      id: 'fundamentals_13',
      topicId: 'fundamentals',
      number: 13,
      difficulty: 'Senior',
      modifier: null,
      position: { x: 85, y: 20 },
      connections: ['fundamentals_14'],
    },
    {
      id: 'fundamentals_14',
      topicId: 'fundamentals',
      number: 14,
      difficulty: 'Senior',
      modifier: null,
      position: { x: 90, y: 30 },
      connections: ['fundamentals_15'],
    },
    {
      id: 'fundamentals_15',
      topicId: 'fundamentals',
      number: 15,
      difficulty: 'Expert',
      modifier: null,
      position: { x: 93, y: 50 },
      connections: [],
    },
  ],
  functions_context: [
    {
      id: 'functions_context_1',
      topicId: 'functions_context',
      number: 1,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 15, y: 25 },
      connections: ['functions_context_2'],
    },
    {
      id: 'functions_context_2',
      topicId: 'functions_context',
      number: 2,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 20, y: 25 },
      connections: ['functions_context_3'],
    },
    {
      id: 'functions_context_3',
      topicId: 'functions_context',
      number: 3,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 25, y: 25 },
      connections: ['functions_context_4'],
    },
    {
      id: 'functions_context_4',
      topicId: 'functions_context',
      number: 4,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 30, y: 40 },
      connections: ['functions_context_6'],
    },
    {
      id: 'functions_context_5',
      topicId: 'functions_context',
      number: 5,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 35, y: 40 },
      connections: ['functions_context_5'],
    },
    {
      id: 'functions_context_6',
      topicId: 'functions_context',
      number: 6,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 40, y: 40 },
      connections: ['functions_context_7'],
    },
    {
      id: 'functions_context_7',
      topicId: 'functions_context',
      number: 7,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 45, y: 55 },
      connections: ['functions_context_8'],
    },
    {
      id: 'functions_context_8',
      topicId: 'functions_context',
      number: 8,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 50, y: 55 },
      connections: ['functions_context_9'],
    },
    {
      id: 'functions_context_9',
      topicId: 'functions_context',
      number: 9,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 55, y: 55 },
      connections: ['functions_context_10'],
    },
    {
      id: 'functions_context_10',
      topicId: 'functions_context',
      number: 10,
      difficulty: 'Senior',
      modifier: null,
      position: { x: 60, y: 70 },
      connections: ['functions_context_11'],
    },
    {
      id: 'functions_context_11',
      topicId: 'functions_context',
      number: 11,
      difficulty: 'Senior',
      modifier: null,
      position: { x: 65, y: 70 },
      connections: ['functions_context_12'],
    },
    {
      id: 'functions_context_12',
      topicId: 'functions_context',
      number: 12,
      difficulty: 'Senior',
      modifier: null,
      position: { x: 70, y: 70 },
      connections: ['functions_context_13'],
    },
    {
      id: 'functions_context_13',
      topicId: 'functions_context',
      number: 13,
      difficulty: 'Expert',
      modifier: null,
      position: { x: 75, y: 85 },
      connections: ['functions_context_14'],
    },
    {
      id: 'functions_context_14',
      topicId: 'functions_context',
      number: 14,
      difficulty: 'Expert',
      modifier: null,
      position: { x: 80, y: 85 },
      connections: ['functions_context_15'],
    },
    {
      id: 'functions_context_15',
      topicId: 'functions_context',
      number: 15,
      difficulty: 'Expert',
      modifier: null,
      position: { x: 85, y: 85 },
      connections: ['functions_context_16'],
    },
  ],
  data_handling: [
    {
      id: 'data_handling_1',
      topicId: 'data_handling',
      number: 1,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 50, y: 7 },
      connections: ['data_handling_2'],
    },
    {
      id: 'data_handling_2',
      topicId: 'data_handling',
      number: 2,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 66.5, y: 28 },
      connections: ['data_handling_3'],
    },
    {
      id: 'data_handling_3',
      topicId: 'data_handling',
      number: 3,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 66.5, y: 72 },
      connections: ['data_handling_4'],
    },
    {
      id: 'data_handling_4',
      topicId: 'data_handling',
      number: 4,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 50, y: 93 },
      connections: ['data_handling_5'],
    },
    {
      id: 'data_handling_5',
      topicId: 'data_handling',
      number: 5,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 33.5, y: 72 },
      connections: ['data_handling_6'],
    },
    {
      id: 'data_handling_6',
      topicId: 'data_handling',
      number: 6,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 33.5, y: 29 },
      connections: ['data_handling_7'],
    },
    {
      id: 'data_handling_7',
      topicId: 'data_handling',
      number: 7,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 39, y: 36 },
      connections: ['data_handling_8'],
    },
    {
      id: 'data_handling_8',
      topicId: 'data_handling',
      number: 8,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 50, y: 22 },
      connections: ['data_handling_9'],
    },
    {
      id: 'data_handling_9',
      topicId: 'data_handling',
      number: 9,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 61, y: 36 },
      connections: ['data_handling_10'],
    },
    {
      id: 'data_handling_10',
      topicId: 'data_handling',
      number: 10,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 61, y: 63 },
      connections: ['data_handling_11'],
    },
    {
      id: 'data_handling_11',
      topicId: 'data_handling',
      number: 11,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 50, y: 79 },
      connections: ['data_handling_12'],
    },
    {
      id: 'data_handling_12',
      topicId: 'data_handling',
      number: 12,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 39, y: 63 },
      connections: ['data_handling_13'],
    },
    {
      id: 'data_handling_13',
      topicId: 'data_handling',
      number: 13,
      difficulty: 'Senior',
      modifier: null,
      position: { x: 44.5, y: 56 },
      connections: ['data_handling_14'],
    },
    {
      id: 'data_handling_14',
      topicId: 'data_handling',
      number: 14,
      difficulty: 'Senior',
      modifier: null,
      position: { x: 44.5, y: 43 },
      connections: ['data_handling_15'],
    },
    {
      id: 'data_handling_15',
      topicId: 'data_handling',
      number: 15,
      difficulty: 'Senior',
      modifier: null,
      position: { x: 50, y: 36 },
      connections: ['data_handling_16'],
    },
    {
      id: 'data_handling_16',
      topicId: 'data_handling',
      number: 16,
      difficulty: 'Expert',
      modifier: null,
      position: { x: 55.5, y: 43 },
      connections: ['data_handling_17'],
    },
    {
      id: 'data_handling_17',
      topicId: 'data_handling',
      number: 17,
      difficulty: 'Expert',
      modifier: null,
      position: { x: 55.5, y: 56 },
      connections: ['data_handling_18'],
    },
    {
      id: 'data_handling_18',
      topicId: 'data_handling',
      number: 18,
      difficulty: 'Expert',
      modifier: null,
      position: { x: 50, y: 64 },
      connections: ['data_handling_19'],
    },
    {
      id: 'data_handling_19',
      topicId: 'data_handling',
      number: 19,
      difficulty: 'Expert',
      modifier: null,
      position: { x: 50, y: 50 },
      connections: [],
    },
  ],
  async_js: [
    {
      id: 'async_js_1',
      topicId: 'async_js',
      number: 1,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 50, y: 0 },
      connections: ['async_js_2'],
    },
    {
      id: 'async_js_2',
      topicId: 'async_js',
      number: 2,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 52.5, y: 10 },
      connections: ['async_js_3'],
    },
    {
      id: 'async_js_3',
      topicId: 'async_js',
      number: 3,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 55, y: 20 },
      connections: ['async_js_4'],
    },
    {
      id: 'async_js_4',
      topicId: 'async_js',
      number: 4,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 57.5, y: 30 },
      connections: ['async_js_5'],
    },
    {
      id: 'async_js_5',
      topicId: 'async_js',
      number: 5,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 60, y: 40 },
      connections: ['async_js_6'],
    },
    {
      id: 'async_js_6',
      topicId: 'async_js',
      number: 6,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 62.5, y: 50 },
      connections: ['async_js_7'],
    },
    {
      id: 'async_js_7',
      topicId: 'async_js',
      number: 7,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 65, y: 60 },
      connections: ['async_js_8'],
    },
    {
      id: 'async_js_8',
      topicId: 'async_js',
      number: 8,
      difficulty: 'Senior',
      modifier: null,
      position: { x: 67.5, y: 70 },
      connections: ['async_js_9'],
    },
    {
      id: 'async_js_9',
      topicId: 'async_js',
      number: 9,
      difficulty: 'Senior',
      modifier: null,
      position: { x: 70, y: 80 },
      connections: ['async_js_10'],
    },
    {
      id: 'async_js_10',
      topicId: 'async_js',
      number: 10,
      difficulty: 'Expert',
      modifier: null,
      position: { x: 72.5, y: 90 },
      connections: [],
    },
  ],
  browser_js: [
    {
      id: 'browser_js_1',
      topicId: 'browser_js',
      number: 1,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 50, y: 0 },
      connections: ['browser_js_2'],
    },
    {
      id: 'browser_js_2',
      topicId: 'browser_js',
      number: 2,
      difficulty: 'Beginner',
      modifier: null,
      position: { x: 50, y: 20 },
      connections: ['browser_js_3', 'browser_js_6'],
    },
    {
      id: 'browser_js_3',
      topicId: 'browser_js',
      number: 3,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 30, y: 40 },
      connections: ['browser_js_4', 'browser_js_5'],
    },
    {
      id: 'browser_js_4',
      topicId: 'browser_js',
      number: 4,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 20, y: 60 },
      connections: [],
    },
    {
      id: 'browser_js_5',
      topicId: 'browser_js',
      number: 5,
      difficulty: 'Junior',
      modifier: null,
      position: { x: 40, y: 60 },
      connections: [],
    },
    {
      id: 'browser_js_6',
      topicId: 'browser_js',
      number: 6,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 70, y: 40 },
      connections: ['browser_js_7', 'browser_js_8'],
    },
    {
      id: 'browser_js_7',
      topicId: 'browser_js',
      number: 7,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 60, y: 60 },
      connections: [],
    },
    {
      id: 'browser_js_8',
      topicId: 'browser_js',
      number: 8,
      difficulty: 'Middle',
      modifier: null,
      position: { x: 80, y: 60 },
      connections: ['browser_js_9', 'browser_js_10'],
    },
    {
      id: 'browser_js_9',
      topicId: 'browser_js',
      number: 9,
      difficulty: 'Senior',
      modifier: null,
      position: { x: 70, y: 80 },
      connections: [],
    },
    {
      id: 'browser_js_10',
      topicId: 'browser_js',
      number: 10,
      difficulty: 'Expert',
      modifier: null,
      position: { x: 90, y: 80 },
      connections: [],
    },
  ],
};
