export const questions = [
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which keyword declares a block-scoped variable in JavaScript?',
    options: [
      { id: 'a', text: 'var' },
      { id: 'b', text: 'let' },
      { id: 'c', text: 'const' },
      { id: 'd', text: 'both let and const' },
    ],
    correct: 'd',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'What is the result of typeof null?',
    options: [
      { id: 'a', text: 'null' },
      { id: 'b', text: 'object' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'string' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which of these is NOT a JavaScript data type?',
    options: [
      { id: 'a', text: 'number' },
      { id: 'b', text: 'string' },
      { id: 'c', text: 'float' },
      { id: 'd', text: 'boolean' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'What will console.log(0.1 + 0.2 === 0.3) print?',
    options: [
      { id: 'a', text: 'true' },
      { id: 'b', text: 'false' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'NaN' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which operator checks both value and type for equality?',
    options: [
      { id: 'a', text: '==' },
      { id: 'b', text: '===' },
      { id: 'c', text: '!=' },
      { id: 'd', text: '=' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'What is the output of Boolean("")?',
    options: [
      { id: 'a', text: 'true' },
      { id: 'b', text: 'false' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'null' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which value is NOT falsy in JavaScript?',
    options: [
      { id: 'a', text: '0' },
      { id: 'b', text: '""' },
      { id: 'c', text: 'false' },
      { id: 'd', text: '"false"' },
    ],
    correct: 'd',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which keyword declares a constant in JavaScript?',
    options: [
      { id: 'a', text: 'let' },
      { id: 'b', text: 'const' },
      { id: 'c', text: 'var' },
      { id: 'd', text: 'constant' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'What does the following code print?\nconsole.log(typeof undefined);',
    options: [
      { id: 'a', text: '"null"' },
      { id: 'b', text: '"object"' },
      { id: 'c', text: '"undefined"' },
      { id: 'd', text: '"void"' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which method adds an element to the end of an array?',
    options: [
      { id: 'a', text: 'push()' },
      { id: 'b', text: 'unshift()' },
      { id: 'c', text: 'append()' },
      { id: 'd', text: 'add()' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which statement creates a loop that runs exactly 10 times?',
    options: [
      { id: 'a', text: 'for (let i = 0; i < 10; i++)' },
      { id: 'b', text: 'while (i < 10)' },
      { id: 'c', text: 'do { ... } while (i < 10)' },
      { id: 'd', text: 'for (let i = 1; i <= 10; i++)' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'What is hoisting in JavaScript?',
    options: [
      { id: 'a', text: 'Moving variable and function declarations to the top of their scope' },
      { id: 'b', text: 'Copying objects' },
      { id: 'c', text: 'Deleting variables from memory' },
      { id: 'd', text: 'A type of loop' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which operator is used for strict inequality?',
    options: [
      { id: 'a', text: '!=="' },
      { id: 'b', text: '!=' },
      { id: 'c', text: '<>' },
      { id: 'd', text: 'not' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'What is the result of "5" + 2 in JavaScript?',
    options: [
      { id: 'a', text: '7' },
      { id: 'b', text: '52' },
      { id: 'c', text: 'NaN' },
      { id: 'd', text: 'undefined' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which value is NOT truthy?',
    options: [
      { id: 'a', text: '[]' },
      { id: 'b', text: '{}' },
      { id: 'c', text: '0' },
      { id: 'd', text: '"hello"' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which keyword declares a function-scoped variable?',
    options: [
      { id: 'a', text: 'let' },
      { id: 'b', text: 'const' },
      { id: 'c', text: 'var' },
      { id: 'd', text: 'function' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'What is the result of Number("123")?',
    options: [
      { id: 'a', text: '123' },
      { id: 'b', text: '"123"' },
      { id: 'c', text: 'NaN' },
      { id: 'd', text: 'undefined' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'What is the scope of a variable declared with let inside a function?',
    options: [
      { id: 'a', text: 'Global' },
      { id: 'b', text: 'Block' },
      { id: 'c', text: 'Function' },
      { id: 'd', text: 'Module' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which statement is true about type coercion in JavaScript?',
    options: [
      { id: 'a', text: 'JavaScript never converts types automatically' },
      { id: 'b', text: 'Type coercion can happen implicitly' },
      { id: 'c', text: 'You must always use Number() or String()' },
      { id: 'd', text: 'Type coercion only works with arrays' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which of the following is a valid if statement?',
    options: [
      { id: 'a', text: 'if x = 5' },
      { id: 'b', text: 'if (x == 5)' },
      { id: 'c', text: 'if x == 5 then' },
      { id: 'd', text: 'if x === 5:' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'What is the output of: console.log(typeof NaN);',
    options: [
      { id: 'a', text: 'number' },
      { id: 'b', text: 'NaN' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'object' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    text: 'Which block will always execute at least once?',
    options: [
      { id: 'a', text: 'for' },
      { id: 'b', text: 'while' },
      { id: 'c', text: 'do...while' },
      { id: 'd', text: 'if' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'Which keyword creates a variable whose value cannot be reassigned?',
    options: [
      { id: 'a', text: 'let' },
      { id: 'b', text: 'const' },
      { id: 'c', text: 'var' },
      { id: 'd', text: 'static' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'What is the output of typeof NaN?',
    options: [
      { id: 'a', text: 'number' },
      { id: 'b', text: 'NaN' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'object' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'Which of the following is NOT a primitive type in JavaScript?',
    options: [
      { id: 'a', text: 'string' },
      { id: 'b', text: 'number' },
      { id: 'c', text: 'object' },
      { id: 'd', text: 'boolean' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'What does the === operator check?',
    options: [
      { id: 'a', text: 'Value only' },
      { id: 'b', text: 'Type only' },
      { id: 'c', text: 'Value and type' },
      { id: 'd', text: 'Nothing' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'Which value is considered falsy?',
    options: [
      { id: 'a', text: '0' },
      { id: 'b', text: '"false"' },
      { id: 'c', text: '[]' },
      { id: 'd', text: '{}'},
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'What is the result of Boolean("0")?',
    options: [
      { id: 'a', text: 'true' },
      { id: 'b', text: 'false' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'null' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'Which statement correctly checks if a variable x is not equal to 10?',
    options: [
      { id: 'a', text: 'x != 10' },
      { id: 'b', text: 'x !== 10' },
      { id: 'c', text: 'x =! 10' },
      { id: 'd', text: 'a and b' },
    ],
    correct: 'd',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'What is the scope of a variable declared with var inside a function?',
    options: [
      { id: 'a', text: 'Block' },
      { id: 'b', text: 'Function' },
      { id: 'c', text: 'Global' },
      { id: 'd', text: 'Module' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'Which loop will always execute at least once?',
    options: [
      { id: 'a', text: 'for' },
      { id: 'b', text: 'while' },
      { id: 'c', text: 'do...while' },
      { id: 'd', text: 'if' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'What does hoisting do with function declarations?',
    options: [
      { id: 'a', text: 'Moves them to the top of their scope' },
      { id: 'b', text: 'Deletes them' },
      { id: 'c', text: 'Ignores them' },
      { id: 'd', text: 'Throws an error' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'Which operator is used for logical AND?',
    options: [
      { id: 'a', text: '&&' },
      { id: 'b', text: '||' },
      { id: 'c', text: '!' },
      { id: 'd', text: '&' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'What is the output of: let x; console.log(x);',
    options: [
      { id: 'a', text: 'null' },
      { id: 'b', text: 'undefined' },
      { id: 'c', text: '0' },
      { id: 'd', text: 'false' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'Which statement is true about let and const?',
    options: [
      { id: 'a', text: 'They are block-scoped' },
      { id: 'b', text: 'They are function-scoped' },
      { id: 'c', text: 'They are global-scoped' },
      { id: 'd', text: 'They are only for numbers' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'What is the result of 2 + "2"?',
    options: [
      { id: 'a', text: '4' },
      { id: 'b', text: '22' },
      { id: 'c', text: 'NaN' },
      { id: 'd', text: 'undefined' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'Which of the following is NOT a valid way to declare a variable?',
    options: [
      { id: 'a', text: 'let x = 5;' },
      { id: 'b', text: 'const y = 10;' },
      { id: 'c', text: 'var z = 1;' },
      { id: 'd', text: 'variable a = 2;' },
    ],
    correct: 'd',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'What is the output of: Boolean([])?',
    options: [
      { id: 'a', text: 'true' },
      { id: 'b', text: 'false' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'null' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'Which value is NOT primitive?',
    options: [
      { id: 'a', text: 'string' },
      { id: 'b', text: 'number' },
      { id: 'c', text: 'object' },
      { id: 'd', text: 'boolean' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'What is the result of null == undefined?',
    options: [
      { id: 'a', text: 'true' },
      { id: 'b', text: 'false' },
      { id: 'c', text: 'TypeError' },
      { id: 'd', text: 'NaN' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'Which statement is true about hoisting?',
    options: [
      { id: 'a', text: 'var declarations are hoisted' },
      { id: 'b', text: 'let/const are not initialized until evaluated' },
      { id: 'c', text: 'function declarations are hoisted' },
      { id: 'd', text: 'All of the above' },
    ],
    correct: 'd',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    text: 'What is the output of: typeof undefined?',
    options: [
      { id: 'a', text: 'undefined' },
      { id: 'b', text: 'null' },
      { id: 'c', text: 'object' },
      { id: 'd', text: 'string' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'What happens if you try to redeclare a let variable in the same scope?',
    options: [
      { id: 'a', text: 'It overwrites the previous value' },
      { id: 'b', text: 'It throws a SyntaxError' },
      { id: 'c', text: 'It is ignored' },
      { id: 'd', text: 'It creates a new variable' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'What is the output of: typeof function(){}',
    options: [
      { id: 'a', text: 'object' },
      { id: 'b', text: 'function' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'string' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'Which statement about const is true?',
    options: [
      { id: 'a', text: 'You cannot change the value of a const variable' },
      { id: 'b', text: 'You cannot reassign the variable, but you can mutate its object properties' },
      { id: 'c', text: 'const is function-scoped' },
      { id: 'd', text: 'const variables are hoisted and initialized to undefined' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'What is the result of: [] == false?',
    options: [
      { id: 'a', text: 'true' },
      { id: 'b', text: 'false' },
      { id: 'c', text: 'TypeError' },
      { id: 'd', text: 'undefined' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'Which of the following is NOT a valid JavaScript loop?',
    options: [
      { id: 'a', text: 'for...of' },
      { id: 'b', text: 'for...in' },
      { id: 'c', text: 'forEach' },
      { id: 'd', text: 'for...to' },
    ],
    correct: 'd',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'What is the output of: null === undefined?',
    options: [
      { id: 'a', text: 'true' },
      { id: 'b', text: 'false' },
      { id: 'c', text: 'TypeError' },
      { id: 'd', text: 'undefined' },
    ],
    correct: 'b',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'Which value is NOT considered falsy?',
    options: [
      { id: 'a', text: '0' },
      { id: 'b', text: 'NaN' },
      { id: 'c', text: '"0"' },
      { id: 'd', text: 'undefined' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'What is the output of: typeof Symbol()',
    options: [
      { id: 'a', text: 'symbol' },
      { id: 'b', text: 'object' },
      { id: 'c', text: 'string' },
      { id: 'd', text: 'function' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'Which operator can be used to check if a property exists in an object?',
    options: [
      { id: 'a', text: 'in' },
      { id: 'b', text: 'has' },
      { id: 'c', text: 'exists' },
      { id: 'd', text: 'contains' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'What is the output of: !![]?',
    options: [
      { id: 'a', text: 'true' },
      { id: 'b', text: 'false' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'NaN' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'Which variable declaration is hoisted and initialized to undefined?',
    options: [
      { id: 'a', text: 'let' },
      { id: 'b', text: 'const' },
      { id: 'c', text: 'var' },
      { id: 'd', text: 'function' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'What is the output of: typeof null?',
    options: [
      { id: 'a', text: 'object' },
      { id: 'b', text: 'null' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'string' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'Which statement about block scope is true?',
    options: [
      { id: 'a', text: 'let and const are block-scoped' },
      { id: 'b', text: 'var is block-scoped' },
      { id: 'c', text: 'All variables are block-scoped' },
      { id: 'd', text: 'None of the above' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'What is the result of: "5" - 2?',
    options: [
      { id: 'a', text: '3' },
      { id: 'b', text: 'NaN' },
      { id: 'c', text: '52' },
      { id: 'd', text: 'undefined' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'Which of the following is NOT a valid comparison operator?',
    options: [
      { id: 'a', text: '===' },
      { id: 'b', text: '!==' },
      { id: 'c', text: '<=>' },
      { id: 'd', text: '!=' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'What is the output of: Boolean("false")?',
    options: [
      { id: 'a', text: 'true' },
      { id: 'b', text: 'false' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'null' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'Which variable declaration will throw a ReferenceError if accessed before initialization?',
    options: [
      { id: 'a', text: 'var' },
      { id: 'b', text: 'let' },
      { id: 'c', text: 'const' },
      { id: 'd', text: 'b and c' },
    ],
    correct: 'd',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'What is the output of: 0 == ""?',
    options: [
      { id: 'a', text: 'true' },
      { id: 'b', text: 'false' },
      { id: 'c', text: 'TypeError' },
      { id: 'd', text: 'undefined' },
    ],
    correct: 'a',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'Which of the following is NOT a valid way to create a loop?',
    options: [
      { id: 'a', text: 'for' },
      { id: 'b', text: 'while' },
      { id: 'c', text: 'repeat' },
      { id: 'd', text: 'do...while' },
    ],
    correct: 'c',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Middle',
    text: 'What is the output of: typeof []?',
    options: [
      { id: 'a', text: 'object' },
      { id: 'b', text: 'array' },
      { id: 'c', text: 'undefined' },
      { id: 'd', text: 'function' },
    ],
    correct: 'a',
  },

  //drag-and-drop questions

  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    type: 'order',
    text: 'Put the steps of a JS event loop tick in the correct order:',
    options: [
      { id: 'a', text: 'Run a task from the task queue' },
      { id: 'b', text: 'Run all microtasks (Promise callbacks)' },
      { id: 'c', text: 'Render / paint (if needed)' },
      { id: 'd', text: 'Wait for the next task' },
    ],
    correct: 'a,b,c,d',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Beginner',
    type: 'order',
    text: 'Order the steps of declaring and calling a function:',
    options: [
      { id: 'a', text: 'Write the function keyword' },
      { id: 'b', text: 'Give the function a name' },
      { id: 'c', text: 'Define the function body in {}' },
      { id: 'd', text: 'Call the function by name with ()' },
    ],
    correct: 'a,b,c,d',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    type: 'order',
    text: 'Put these Promise chain steps in the correct order:',
    options: [
      { id: 'a', text: 'Create a Promise with new Promise(...)' },
      { id: 'b', text: 'Chain .then() to handle resolved value' },
      { id: 'c', text: 'Chain .catch() to handle rejection' },
      { id: 'd', text: 'Chain .finally() to run cleanup' },
    ],
    correct: 'a,b,c,d',
  },
  {
    topic: 'fundamentals',
    difficulty: 'Junior',
    type: 'order',
    text: 'Order the steps of making a fetch() request correctly:',
    options: [
      { id: 'a', text: 'Call fetch(url)' },
      { id: 'b', text: 'Await / .then() to get the Response' },
      { id: 'c', text: 'Call response.json() to parse body' },
      { id: 'd', text: 'Use the resulting data' },
    ],
    correct: 'a,b,c,d',
  },
  {
    topic: 'fundamentals',
    difficulty: '',
    type: 'order',
    text: 'Order the JavaScript scope chain lookup steps:',
    options: [
      { id: 'a', text: 'Look in the local function scope' },
      { id: 'b', text: 'Look in any outer (closure) scopes' },
      { id: 'c', text: 'Look in the module scope' },
      { id: 'd', text: 'Look in the global scope' },
    ],
    correct: 'a,b,c,d',
  },
];
